apiVersion: v1
kind: Service
metadata:
  name: gmc-service
spec:
  selector:
    app: gmc
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gmc
spec:
  selector:
    matchLabels:
      app: gmc
  serviceName: "gmc-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: gmc
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: install
          image: busybox
          command:
            - chmod
            - "777"
            - "/gmc"
          volumeMounts:
            - name: gmc
              mountPath: "/gmc"
      containers:
        - name: gmc
          image: gemfire/gemfire-management-console:1.2.1
          ports:
            - containerPort: 8080
              name: gmc
          volumeMounts:
            - name: gmc
              mountPath: /opt/gemfire/VMware_GemFire_Management_Console
  volumeClaimTemplates:
    - metadata:
        name: gmc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName:
        resources:
          requests:
            storage: 10Gi